spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: 8f64df72-c7c1-48f3-8a6e-2c9c0835d9dd
            client-secret: 3-N0iHGt2~0qCi3w7vMvsbNt-5~2g6CuTT
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/azure'
            scope:
              - openid
              - profile
server:
  forward-headers-strategy: native